#!/usr/bin/env python
import gitcommitlib, os

def parse_options():
    from optparse import OptionParser
    parser = OptionParser()
    parser.add_option('-v', dest='show_version', action='store_true')
    (options, args) = parser.parse_args()
    return options

if __name__ == '__main__':
    options = parse_options()
    if options.show_version:
        print "Version %s" % gitcommitlib.get_version()
        exit()
    gitcommitlib.check_for_todos()
    gitcommitlib.run_tests()
    os.system("git commit -a -v")    
